# Generated by Django 6.0.3 on 2026-05-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (англ.)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (англ.)'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО (англ.)'),
        ),
    ]
