# Generated by Django 6.0.3 on 2026-05-31 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_add_english_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='club.trainer', verbose_name='Предпочитаемый тренер'),
        ),
    ]
