# Generated by Django 6.0.3 on 2026-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_add_preferred_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='specialist_trainers', to='club.service', verbose_name='Услуги тренера'),
        ),
    ]
